name = "test_cf_worker" # todo
main = "build/worker/shim.mjs"
compatibility_date = "2022-01-20"

kv_namespaces = [
  { binding = "KVSTORE", id = "88c20d05775e4317bc0fdabbe0ed1d2b", preview_id = "88c20d05775e4317bc0fdabbe0ed1d2b" }
]

[vars]
WORKERS_RS_VERSION = "0.0.11"

[build]
command = "cargo install -q worker-build && worker-build --release"
